apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbox-pv-volume
  labels:
    type: local
spec:
  storageClassName: netbox
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/netbox/data"
